### ISSUE TITLE
WSS support

### ISSUE THREAD

**Issue by ThrottleLP** [bitfocus/companion-module-generic-websocket#11] opened 2022-08-11 20:11 UTC
I have to communicate with an external hosted service. At the moment, it is not possible to connect to a Secure Websocket, which is really annoying because I don't want to send control and data requests unencrypted and unprotected through the web.

Maybe you could add a checkbox "secure connection" or something like that?
if (this.config.secure) {
this.ws = new WebSocket(`wss://${ip}:${port}`)
} else {
this.ws = new WebSocket(`ws://${ip}:${port}`)
}

**Comment by krzyc** [comment] 2022-08-12 08:03
Duplicate of #10

**Comment by krzyc** [comment] 2022-08-12 08:04
I will try to fix it as described in #10 as soon as possible.

**Closed as completed by krzyc** 2022-08-12 08:04 UTC
Labels: duplicate
